(defalias 'dk 'describe-key)
(defalias 'dkb 'describe-key-briefly)
(defalias 'db 'describe-bindings)
(defalias 'dfa 'describe-face)
(defalias 'df 'describe-function)
(defalias 'dv 'describe-variable)
(defalias 'dm 'describe-mode)
(defalias 'ir 'indent-region)
(defalias 'ap 'apropos)
(defalias 'ff 'find-function)
(defalias 'kb 'kill-buffer)
(defalias 'kemacs 'kill-emacs)
(defalias 'id 'insert-date-time)
(defalias 'rb 'revert-buffer)
(defalias 'md 'make-directory)
(defalias 'cp 'dired-do-copy)
(defalias 'mv 'dired-do-rename)
(defalias 'cr 'comment-region)
(defalias 'ucr 'uncomment-region)

(provide 'alias-init)
