(defalias 'dk 'describe-key)
(defalias 'dkb 'describe-key-briefly)
(defalias 'db 'describe-bindings)
(defalias 'df 'describe-function)
(defalias 'dv 'describe-variable)
(defalias 'dm 'describe-mode)
(defalias 'ir 'indent-region)
(defalias 'ap 'apropos)
(defalias 'ff 'find-function)
(defalias 'kb 'kill-buffer)
(defalias 'id 'insert-date-time)
(provide 'alias-init)
